---
# Some general information about this Freifunk community
community: 'bodensee'
community_name: 'Bodensee'
community_shortname: 'ffbsee'

# Some tecnical information like internal IP Adresses
### FYI: We use new addresses on B.A.T.M.A.N. V
ipv6_prefix: 'fdef:1701:b5ee:23:'
ipv4_netz: '10.15.224.0/20'
ipv4_dhcp_server: '10.15.224.1'
ipv4_dhcp_interface: 'bat0'

# some more advanced informations like B.A.T.M.A.N Download Informations
batman_version: '2025.4'
batman_sha256sum: '62490a8f8b58c02e819216f3e963249984645d3e460156a043b73fc53e24f86d'
 # https://downloads.open-mesh.org/batman/releases/batman-adv-{{ batman_version }}/batman-adv-{{ batman_version }}.tar.gz
batctl_sha256sum: '566aa4fd74355e8d5dd2bd21c25e98cc068e77fd08e19f80b8e2b5edde7c8e65'
 # https://downloads.open-mesh.org/batman/releases/batman-adv-{{ batman_version }}/batctl-{{ batman_version }}.tar.gz
alfred_sha256sum: '8375475478ed1cd4139c9000175a7d1407ee8dd919a0b7c9dbf7d15095880485'
 # https://downloads.open-mesh.org/batman/stable/sources/alfred/alfred-{{ batman_version }}.tar.gz'

fastd_url: 'https://github.com/neocturne/fastd/releases/download/v23/fastd-23.tar.xz'
fastd_checksum: 'dcab54485c79dda22ce6308a2a48764d53977a518952facd1204ba21af1c86e0'
fastd_build_dir: '/tmp/fastd'
fastd_version: 23

wireguard_remote_directory: "/etc/wireguard" 
wireguard_port: "51820"
wireguard_interface: "wg-backbone"
wireguard_service_enabled: "yes"
wireguard_service_state: "started"
wireguard_interface_restart: true

# technical informations for TLS
letsencrypt_email: 'kommunikation@ffbsee.de'

only_allow_ed25519: false 
