---

- name: Create freifunk directory
  file:
    path: '/opt/freifunk'
    state: 'directory'
    mode: 'u=rwx,g=rx,o=rx'

- name: Get the MAC address
  set_fact:
    mac_address: "{{ hostvars[inventory_hostname]['ansible_' + wan_base_interface]['macaddress'] }}"

- name: Copy freifunk update script
  template:
    src: 'templates/freifunk-files/update.sh'
    dest: '/opt/freifunk/update.sh'
    owner: 'root'
    group: 'root'
    mode: 'u=rwx,g=rx,o=rx'

- name: Create freifunk-update.service
  ansible.builtin.copy:
    dest: /etc/systemd/system/freifunk-update.service
    owner: root
    group: root
    mode: '0644'
    content: |
      [Unit]
      Description=Freifunk periodic update script
      After=wg-quick@wg-backbone.service
      Wants=wg-quick@wg-backbone.service

      [Service]
      Type=oneshot
      User=root
      Group=root
      ExecStart=/opt/freifunk/update.sh

- name: Create freifunk-update.timer
  ansible.builtin.copy:
    dest: /etc/systemd/system/freifunk-update.timer
    owner: root
    group: root
    mode: '0644'
    content: |
      [Unit]
      Description=Run Freifunk update.sh every 5 minutes

      [Timer]
      OnBootSec=1min
      OnUnitActiveSec=5min
      AccuracySec=30s
      Persistent=true

      [Install]
      WantedBy=timers.target
  notify: Reload systemd units

- name: Enable and start freifunk-update.timer
  ansible.builtin.systemd:
    name: freifunk-update.timer
    enabled: true
    state: started


- name: Copy map-backend.py (deprecated, but required)
  copy:
    src: 'files/freifunk-files/map-backend.py'
    dest: '/opt/freifunk/map-backend.py'
    owner: 'root'
    group: 'root'
    mode: 'u=rwx,g=rx,o=rx'

- name: Copy ffmap-d3.jq (deprecated, but required)
  copy:
    src: 'files/freifunk-files/ffmap-d3.jq'
    dest: '/opt/freifunk/ffmap-d3.jq'
    owner: 'root'
    group: 'root'
    mode: 'u=rwx,g=rx,o=rx'

- name: Copy status_page_create.sh (deprecated, but required)
  copy:
    src: 'files/freifunk-files/status_page_create.sh'
    dest: '/opt/freifunk/status_page_create.sh'
    owner: 'root'
    group: 'root'
    mode: 'u=rwx,g=rx,o=rx'

- name: Copy counter_update.py (deprecated, but required)
  copy:
    src: 'files/freifunk-files/counter_update.py'
    dest: '/opt/freifunk/counter_update.py'
    owner: 'root'
    group: 'root'
    mode: 'u=rwx,g=rx,o=rx'

- name: get v2_map-backend.py
  get_url:
    url: 'https://raw.githubusercontent.com/freifunk-bielefeld/server-config/e1e738f0f3c3c66f9f6dc2106709f834fcc27eff/freifunk/map-backend.py'
    dest: '/opt/freifunk/v2_map-backend.py'
    checksum: sha256:6cf31c290c6d3001e190caf94dcdb273bb68d7bd162c1643f944f26df54a40b5
    mode: '750'

